apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: stage-catsrc
  namespace: openshift-marketplace
spec:
  displayName: Production Operators
  image: 	brew.registry.redhat.io/rh-osbs/iib-pub:v4.18
  publisher: OpenShift Dev
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 15m
