{
 "title": "Power Monitor Dashboard",
 "description": "Dashboard for Power Monitor",
 "tags": [ "power-monitor-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kepler_node_cpu_info{job=\"$job\"}, instance)"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(kepler_node_cpu_watts{job=\"$job\"}, zone)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kepler_pod_cpu_watts{job=\"$job\"}, pod_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_pod_cpu_watts{job=\"$job\", pod_namespace=~\"$namespace\"},pod_name)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kepler_pod_cpu_watts,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RAPL Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAPL Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (node_name,zone)(kepler_node_cpu_watts{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (instance, model_name)(kepler_node_cpu_info{job=\"$job\"})"
    }
   ]
  },
  { "title": "Cluster Wide Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Power Consumption of Cluster",
   "type": "gauge",
   "description": "Total Power Consumption of the Cluster. Using Psys power to depict the total power. Will use Package if Psys is not available",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# 1. Sum 'psys' from nodes that HAVE 'psys'\n(sum(\n  kepler_node_cpu_watts{zone=\"psys\"}\n) or vector(0))\n+\n# 2. Sum 'package' from nodes that DO NOT HAVE 'psys'\n(sum(\n  kepler_node_cpu_watts{zone=\"package\"}\n  unless on(node_name)\n  kepler_node_cpu_watts{zone=\"psys\"}\n) or vector(0))\n+\n# 3. Sum 'dram' from ALL nodes that have it\n(sum(\n  kepler_node_cpu_watts{zone=\"dram\"}\n) or vector(0))",
     "legendFormat": "Total"
    },
    {
     "expr": "# 1. Sum 'psys' from nodes that HAVE 'psys'\n(sum(\n  kepler_node_cpu_active_watts{zone=\"psys\"}\n) or vector(0))\n+\n# 2. Sum 'package' from nodes that DO NOT HAVE 'psys'\n(sum(\n  kepler_node_cpu_active_watts{zone=\"package\"}\n  unless on(node_name)\n  kepler_node_cpu_active_watts{zone=\"psys\"}\n) or vector(0))\n+\n# 3. Sum 'dram' from ALL nodes that have it\n(sum(\n  kepler_node_cpu_active_watts{zone=\"dram\"}\n) or vector(0))",
     "legendFormat": "Active"
    },
    {
     "expr": "# 1. Sum 'psys' from nodes that HAVE 'psys'\n(sum(\n  kepler_node_cpu_idle_watts{zone=\"psys\"}\n) or vector(0))\n+\n# 2. Sum 'package' from nodes that DO NOT HAVE 'psys'\n(sum(\n  kepler_node_cpu_idle_watts{zone=\"package\"}\n  unless on(node_name)\n  kepler_node_cpu_idle_watts{zone=\"psys\"}\n) or vector(0))\n+\n# 3. Sum 'dram' from ALL nodes that have it\n(sum(\n  kepler_node_cpu_idle_watts{zone=\"dram\"}\n) or vector(0))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Current Total Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (zone,node_name) (kepler_node_cpu_watts{job=\"$job\", zone=~\"$zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Active Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (zone,node_name) (kepler_node_cpu_active_watts{job=\"$job\", zone=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "Current Idle Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (zone,node_name) (kepler_node_cpu_idle_watts{job=\"$job\", zone=~\"$zone\"})"
    }
   ]
  },
  { "title": "Node Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top 5 Power Consuming Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk(5,\n  (\n    # Part A: Sum of SoC power (PSYS or PACKAGE) per node\n    (\n      sum by (node_name) (\n        (\n          # A.1: Get PSYS values from PSYS nodes\n          kepler_node_cpu_watts{zone=\"psys\"}\n        )\n        or\n        (\n          # A.2: Get PACKAGE values from non-PSYS nodes\n          kepler_node_cpu_watts{zone=\"package\"}\n          unless on(node_name)\n          kepler_node_cpu_watts{zone=\"psys\"}\n        )\n      ) or vector(0)\n    )\n    +\n    # Part B: Sum of DRAM power from ALL nodes per node\n    (\n      sum by (node_name) (\n        kepler_node_cpu_watts{zone=\"dram\"}\n      ) or vector(0)\n    )\n  ) > 0\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) per Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (zone) (kepler_node_cpu_watts{job=\"$job\", zone=~\"$zone\"})",
     "legendFormat": "Zone - {{zone}}"
    }
   ]
  },
  {
   "title": "Node Power Consumption (W) By Zone For $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_node_cpu_watts{job=\"$job\", instance=~\"$node\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Active Power Consumption (W) By Zone For $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_node_cpu_active_watts{job=\"$job\", instance=~\"$node\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Idle Power Consumption (W) By Zone For $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_node_cpu_idle_watts{job=\"$job\", instance=~\"$node\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  { "title": "Power Monitor - Namespace Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Top 10 Power Consuming Namespaces (W)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk(10,\n  (\n    # Part A: Sum of SoC power (PSYS or PACKAGE) per namespace\n    (\n      sum by (pod_namespace,node_name) (\n        (\n          # A.1: Get PSYS attributions from pods on PSYS nodes\n          kepler_pod_cpu_watts{job=\"$job\", zone=\"psys\"}\n          and on(node_name)\n          kepler_node_cpu_watts{zone=\"psys\"}\n        )\n        or\n        (\n          # A.2: Get PACKAGE attributions from pods on non-PSYS nodes\n          kepler_pod_cpu_watts{job=\"$job\", zone=\"package\"}\n          unless on(node_name)\n          kepler_node_cpu_watts{zone=\"psys\"}\n        )\n      ) or vector(0)\n    )\n    +\n    # Part B: Sum of DRAM power from ALL nodes per namespace\n    (\n      sum by (pod_namespace,node_name) (\n        kepler_pod_cpu_watts{job=\"$job\", zone=\"dram\"}\n      ) or vector(0)\n    )\n  ) > 0  # <--- THIS IS THE FIX\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Power Consumption (W) By Zone For $namespace",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_pod_cpu_watts{job=\"$job\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{pod_name}}"
    }
   ]
  }
 ]
}